git clone git@github.com:wechange-eg/cosinnus-core.git cosinnus-core
git clone git@github.com:wechange-eg/cosinnus-etherpad.git cosinnus-etherpad
git clone git@github.com:wechange-eg/cosinnus-event.git cosinnus-event
git clone git@github.com:wechange-eg/cosinnus-message.git cosinnus-message
git clone git@github.com:wechange-eg/cosinnus-file.git cosinnus-file
git clone git@github.com:wechange-eg/cosinnus-note.git cosinnus-note
git clone git@github.com:wechange-eg/cosinnus-notifications.git cosinnus-notifications
git clone git@github.com:wechange-eg/cosinnus-marketplace.git cosinnus-marketplace
git clone git@github.com:wechange-eg/cosinnus-poll.git cosinnus-poll
git clone git@github.com:wechange-eg/cosinnus-stream.git cosinnus-stream
git clone git@github.com:wechange-eg/cosinnus-todo.git cosinnus-todo
